#!/usr/bin/python3
def raise_exception_msg(message=""):
    """ A function that raises a name exception with a message. """
    # This is how a message is added to a raised exception.
    raise NameError(message)    # The message is saved in a variable 'message'
    # raise NameError("Your message can also go here")

